### ISSUE TITLE
不生效了

### ISSUE THREAD

**Issue by bty552** [xh321/BetterQQNT-Kill-Update#2]
不生效了

**Comment by xh321** [comment]
这个已经观察到了，最近会更新的，请等待

**Comment by xh321** [comment]
更新了一版，似乎，也许解决了，可以看看
版本0.1.2

**Comment by NEKOice** [comment]
mac v6.9.12-10951，启动后会弹出安全提示（qq版本过低），且每次登陆都需要重新扫码，这个是版本的问题还是插件的问题

**Comment by xh321** [comment]
> mac v6.9.12-10951，启动后会弹出安全提示（qq版本过低），且每次登陆都需要重新扫码，这个是版本的问题还是插件的问题

mac版我也不太清楚，能否截图一下QQ版本过低的提示？插件仅拦截更新提示，并不会阻碍其他功能，有可能真的是因为版本过低，可否尝试更新看看能否解决？

**Comment by xh321** [comment]
如果没有问题就先暂时关闭issue了
