### ISSUE TITLE
任务栏右键退出QQ失效

### ISSUE THREAD

**Issue by 16cm** [xh321/BetterQQNT-Kill-Update#3]
QQ 9.9.2-16183 
插件 0.1.4 

任务栏右键退出QQ失效

![image](https://github.com/xh321/LiteLoaderQQNT-Kill-Update/assets/20642702/cca38b8f-accb-4481-9c03-ba9e9f5153de)

**Comment by xh321** [comment]
这与插件无关，有时候QQ卡住会导致退不掉，是框架的偶发情况
